class ContpaqMailingAggregate:
	def __init__(
		self,
		CIDCLIENTEPROVEEDOR=None,
		CCODIGOCLIENTE=None,
		CRAZONSOCIAL=None,
		CFECHAALTA=None,
		CRFC=None,
		CTIMESTAMP=None,
	):
		self.CIDCLIENTEPROVEEDOR = CIDCLIENTEPROVEEDOR
		self.CCODIGOCLIENTE = CCODIGOCLIENTE
		self.CRAZONSOCIAL = CRAZONSOCIAL
		self.CFECHAALTA = CFECHAALTA
		self.CRFC = CRFC
		self.CTIMESTAMP = CTIMESTAMP