class ContpaqArticuloAggregate:
	def __init__(
		self,
		CIDPRODUCTO=None,
		CCODIGOPRODUCTO=None,
		CNOMBREPRODUCTO=None,
		CTIPOPRODUCTO=None,
		CFECHAALTAPRODUCTO=None,
		CFECHABAJA=None,
		CTIMESTAMP=None,
	):
		self.CIDPRODUCTO = CIDPRODUCTO
		self.CCODIGOPRODUCTO = CCODIGOPRODUCTO
		self.CNOMBREPRODUCTO = CNOMBREPRODUCTO
		self.CTIPOPRODUCTO = CTIPOPRODUCTO
		self.CFECHAALTAPRODUCTO = CFECHAALTAPRODUCTO
		self.CFECHABAJA = CFECHABAJA
		self.CTIMESTAMP = CTIMESTAMP