class ContpaqAlbaranVentaLineaAggregate:

	def __init__(
		self,
		CIDMOVIMIENTO,
		CIDDOCUMENTO,
		CNUMEROMOVIMIENTO,
		CIDPRODUCTO,
		CUNIDADES,
		CPRECIO,
		CTOTAL,
		CPORCENTAJEIMPUESTO1,
	):
		self.CIDMOVIMIENTO = CIDMOVIMIENTO
		self.CIDDOCUMENTO = CIDDOCUMENTO
		self.CNUMEROMOVIMIENTO = CNUMEROMOVIMIENTO
		self.CIDPRODUCTO = CIDPRODUCTO
		self.CUNIDADES = CUNIDADES
		self.CPRECIO = CPRECIO
		self.CTOTAL = CTOTAL
		self.CPORCENTAJEIMPUESTO1 = CPORCENTAJEIMPUESTO1