class NetvyPedidoVentaLineaAggregate:
	def __init__(
		self,
		PedidoVentaLineaID=None,
		CustomerID=None,
		EmpresaID=None,
		UsuarioID=None,
		FechaHoraUsuario=None,
		Linea=None,
		TipoLinea=None,
		ArticuloID=None,
		Nombre=None,
		Descripcion=None,
		Cantidad=None,
		PrecioVenta=None,
		Dto1=None,
		Dto2=None,
		Dto3=None,
		ImporteVenta=None,
		PrecioCoste=None,
		Referencia=None,
		NotaInterna=None,
		NotaCliente=None,
		PedidoVentaCabeceraID=None,
		FechaEntregaPrevistaCliente=None,
		FechaEntregaPrevistaInterna=None,
		CantidadOriginal=None,
		CantidadEntregada=None,
		Entregado=None,
		PorcentajeIVA=None,
		PorcentajeRecargo=None,
		OfertaLineaID=None,
		FechaHoraModificado=None,
		Codigo=None,
		CodigoAlternativo=None,
	):
		self.PedidoVentaLineaID = PedidoVentaLineaID
		self.CustomerID = CustomerID
		self.EmpresaID = EmpresaID
		self.UsuarioID = UsuarioID
		self.FechaHoraUsuario = FechaHoraUsuario
		self.Linea = Linea
		self.TipoLinea = TipoLinea
		self.ArticuloID = ArticuloID
		self.Nombre = Nombre
		self.Descripcion = Descripcion
		self.Cantidad = Cantidad
		self.PrecioVenta = PrecioVenta
		self.Dto1 = Dto1
		self.Dto2 = Dto2
		self.Dto3 = Dto3
		self.ImporteVenta = ImporteVenta
		self.PrecioCoste = PrecioCoste
		self.Referencia = Referencia
		self.NotaInterna = NotaInterna
		self.NotaCliente = NotaCliente
		self.PedidoVentaCabeceraID = PedidoVentaCabeceraID
		self.FechaEntregaPrevistaCliente = FechaEntregaPrevistaCliente
		self.FechaEntregaPrevistaInterna = FechaEntregaPrevistaInterna
		self.CantidadOriginal = CantidadOriginal
		self.CantidadEntregada = CantidadEntregada
		self.Entregado = Entregado
		self.PorcentajeIVA = PorcentajeIVA
		self.PorcentajeRecargo = PorcentajeRecargo
		self.OfertaLineaID = OfertaLineaID
		self.FechaHoraModificado = FechaHoraModificado
		self.Codigo = Codigo
		self.CodigoAlternativo = CodigoAlternativo
